#!/bin/bash

printf "GET /path/to/file HTTP/1.1\r\n" >req
printf "Content-Length: 395\r\n" >>req
printf "Accept: text/plain; q=0.5, text/html, text/x-dvi; q=0.8\r\n" >>req
printf "Accept-Charset: iso-8859-5, unicode-1-1;q=0.8\r\n" >> req
printf "Accept-Encoding: compress;q=0.5, gzip;q=1.0\r\n" >> req
printf "Accept-Language: da, en-gb;q=0.8, en;q=0.7\r\n" >> req
printf "Authorization: credentials\r\n" >>req
printf "Cache-Control: no-cache, private=\"field\"\r\n" >>req
printf "Connection: close\r\n" >>req
printf "Content-Encoding: gzip\r\n" >>req
printf "Content-Language: mi, en\r\n" >>req
printf "\r\n" >>req
